### ISSUE TITLE
Getting error when searching indexes

### ISSUE THREAD

**Issue by buddyroo30** [swish-e/swish-e#2]
We use Swish-e in a legacy app, and I got an error today when trying to search against some indexes I had just built: "getTotalWordsInFile passed an invalied file number" (no results passed back, just this error). The only place I could find this is in this Swish-e code file: 

https://www.esa.org/tiee/search/src/db_read.c

What does this error mean and why is it being thrown? Is there anything I could do to fix it (e.g. re-index in some different way, etc.) I actually index in parallel to create multiple indexes, which I use all together with the -f option in searching with swish-e. If I try to just run Swish-e against the individual index files, most work fine, it is just some that fail with this error (and the overall search fails this way when all indexes are used with the -f option).

Anyway, not sure this repo is still being maintained or developed, but thought I'd submit this issue anyway. Thanks for any help/suggestions you can give.

**Comment by karpet** [comment]
This repo is definitely not maintained.

When swish-e.org went offline, I took the latest local snapshot I had of the svn repository and converted it to git and pushed it here. I will mark the repo as archived to prevent misunderstanding in future.
